cloud:
  aws:
    s3:
      bucket: ten-thread
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIA23I3RWAPZ4FL6QL4
      secretKey: 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

spring:
  redis:
    host:localhost
    port:6379
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true
